# common
datadir: '/home/zhmiao/datasets/multipie/cropped'
src: 'mp05'
tgt: 'multi'
tgt_list: ['mp05', 'mp08', 'mp09', 'mp13', 'mp14']

# model
base_model: 'AMN_res'
domain_factor_model: 'DomainFactorBackbone'
num_cls: 6

# optim
betas: [0.9, 0.999]
weight_decay: 0
batch: 128

# source
src_lr: 0.0001
src_num_epoch: 100

# mann
mann_lr: 0.00001
mann_num_epoch: 200

# disentangle
domain_factor_lr: 0.0001
gamma_dispell: 1
gamma_rec: 10
fake_label_type: 'random'
#domain_factor_num_epoch: 400
domain_factor_num_epoch: 200

# scheduled
norm_domain_factor: True
domain_factor_cond: 2
# domain_factor_cond: 3
num_epoch_scheduled: 200
# schedule_strategy: "expand"
schedule_strategy: "shift"
#initial_ratio: 0.5
initial_ratio: 0.5
#power: 0.3
power: 0.3
scheduled_mann_lr: 0.0001
